backend:
  name: git-gateway
  branch: main

site_url: https://loesscafe.netlify.app
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Bu satırı ekle - medya dosyaları için izin
media_library:
  name: uploadcare
  config:
    publicKey: your-uploadcare-key

collections:
  - name: "menu-items"
    label: "Menü Öğeleri"
    folder: "src/data/items"
    create: true
    slug: "{{fields.category}}-{{slug}}"
    format: 'json'
    extension: 'json'
    fields:
      - {label: "İsim", name: "name", widget: "string"}
      - label: "Kategori"
        name: "category"
        widget: "select"
        options:
          - {label: "Sıcak İçecekler", value: "sicakIcecekler"}
          - {label: "Türk Kahvesi", value: "turkKahvesi"}
          - {label: "Sıcak Kahveler", value: "sicakKahveler"}
          - {label: "Soğuk Kahveler", value: "sogukKahveler"}
          - {label: "Frozen & Milkshake", value: "frozenMilkshake"}
          - {label: "Spesiyel", value: "spesiyel"}
          - {label: "Meşrubatlar", value: "mesrubatlar"}
          - {label: "Tatlılar", value: "tatlilar"}
      - {label: "Fiyat", name: "price", widget: "string"}
      - {label: "Açıklama", name: "description", widget: "text"}
      - {label: "Fotoğraf", name: "image", widget: "image"}
      - {label: "ID", name: "id", widget: "number"}

  - name: "cafe-settings"
    label: "Kafe Ayarları"
    files:
      - label: "Genel Bilgiler"
        name: "info"
        file: "src/data/cafeInfo.json"
        fields:
          - {label: "Kafe Adı", name: "name", widget: "string", default: "LOESS"}
          - {label: "Ana Slogan", name: "mainSlogan", widget: "string", default: "Bohem dokunuş, eşsiz lezzet"}
          - {label: "Alt Slogan", name: "subSlogan", widget: "string", default: "Bohem atmosferde lezzet yolculuğu"}
          - {label: "Telefon", name: "phone", widget: "string", default: "0XXX XXX XX XX"}
          - {label: "Açılış Saati", name: "openingTime", widget: "string", default: "14:00"}
          - {label: "Kapanış Saati", name: "closingTime", widget: "string", default: "02:00"}
          - {label: "Logo", name: "logo", widget: "image", required: false}