backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu-items"
    label: "Menü Öğeleri"
    folder: "src/data/items"
    create: true
    slug: "{{category}}-{{slug}}"
    fields:
      - {label: "İsim", name: "name", widget: "string"}
      - label: "Kategori"
        name: "category" 
        widget: "select"
        options:
          - {label: "Kahve", value: "kahve"}
          - {label: "Yemek", value: "yemek"}
          - {label: "İçecek", value: "icecek"}
          - {label: "Tatlı", value: "tatli"}
      - {label: "Fiyat", name: "price", widget: "string", pattern: ["\\d+₺", "Lütfen '45₺' formatında fiyat girin"]}
      - {label: "Açıklama", name: "description", widget: "text"}
      - {label: "Fotoğraf", name: "image", widget: "image"}
      - {label: "Popüler", name: "popular", widget: "boolean", default: false, required: false}
      - {label: "Sıra", name: "order", widget: "number", default: 1, min: 1}

  - name: "cafe-info"
    label: "Kafe Bilgileri"
    files:
      - label: "Genel Bilgiler"
        name: "info"
        file: "src/data/cafeInfo.json"
        fields:
          - {label: "Kafe Adı", name: "name", widget: "string", default: "LOESS"}
          - {label: "Slogan", name: "slogan", widget: "string", default: "Bohem atmosferde lezzet yolculuğu"}
          - {label: "Adres", name: "address", widget: "string"}
          - {label: "Telefon", name: "phone", widget: "string"}
          - {label: "Açılış Saati", name: "opening", widget: "string", default: "08:00"}
          - {label: "Kapanış Saati", name: "closing", widget: "string", default: "22:00"}
          - {label: "Logo", name: "logo", widget: "image", required: false}